function names = featureNames()
%FEATURENAMES  The fixed, ordered names of the eight quality features.  [Phase 3]
%   names = netra.quality.featureNames() returns a 1x8 cellstr in the exact
%   FEATURE ORDER the trained classifier depends on. This is the SINGLE source
%   of truth for the order; extractFeatures, scoreComposite, classifyRuleBased,
%   the trainer, and docs/quality_method.md all refer to it.
%
%   Changing this list changes the model input contract - retrain after any
%   edit. The order is also written into the saved model file (featureNames).

    names = { ...
        'focusLaplacian', ...
        'focusTenengrad', ...
        'illumUniformity', ...
        'saturatedFraction', ...
        'darkFraction', ...
        'fovCompleteness', ...
        'contrastStd', ...
        'localContrast'};
end
