function names = stageNames()
%STAGENAMES  Ordered list of pipeline stage names (single source of truth).
%   names = netra.util.stageNames() returns a cellstr of the nine stage
%   names in pipeline execution order. newCaseRecord uses it to pre-create
%   timing/provenance fields; runPipeline uses it to drive execution.
%
%   Changing pipeline order or stage set means changing this ONE list.

    names = { ...
        'quality', ...
        'preproc', ...
        'structures', ...
        'lesions', ...
        'grading', ...
        'xai', ...
        'routing', ...
        'report', ...
        'store'};
end
