function names = paramNames()
%PARAMNAMES  The 15 masked capacity-model parameter names, in UI/form order.
%   names = netra.sim.paramNames() is the single source of truth for the
%   parameter set shared by the Simulink mask, default_params, buildParams and
%   the Capacity Planner UI form. Changing the parameter set means changing
%   this ONE list (and the mask in simulink/build_netra_capacity.m).

    names = { ...
        'annualPatients', ...
        'campDaysPerYear', ...
        'imagesPerPatient', ...
        'arrivalVariability', ...
        'qualityRejectRate', ...
        'recaptureSuccessRate', ...
        'imageSizeMB', ...
        'bandwidthMbps', ...
        'inferenceSecPerImage', ...
        'processingNodes', ...
        'autoClearRate', ...
        'reviewers', ...
        'reviewSecPerCase', ...
        'reviewerHoursPerDay', ...
        'simDays'};
end
