function cr = newCaseRecord(imagePath, metaStruct)
%NEWCASERECORD  Authoritative caseRecord schema factory for the NETRA pipeline.
%   cr = netra.newCaseRecord(imagePath) builds a fully-populated scalar
%   struct with every field defined in the NETRA data contract, initialised
%   to typed empties or documented defaults.
%
%   cr = netra.newCaseRecord(imagePath, metaStruct) also merges caller
%   metadata. metaStruct is optional; recognised fields are patientID,
%   phcID, age, dmYears, eye. Missing fields get documented defaults.
%
%   This function is the SINGLE source of truth for the caseRecord shape.
%   Every stage adds to this record; no stage defines new top-level groups.
%   See docs/schema.md for the field-by-field contract.
%
%   Errors:
%     NETRA:io:fileNotFound  imagePath does not exist on disk.
%     NETRA:io:unreadable    the file exists but cannot be read as an image.
%
%   Example:
%     cr = netra.newCaseRecord('data/demo/sample01.jpg');

    arguments
        imagePath (1,:) char
        metaStruct struct = struct()
    end

    if ~isfile(imagePath)
        error('NETRA:io:fileNotFound', ...
            'Image not found: %s', imagePath);
    end

    % Phase 2: decode the pixels so meta.imageHash is a REAL content hash and
    % (when a PHC id is supplied) meta.uid is the deterministic ingest id. We
    % do NOT store the pixels in cr.img.raw here - that stays empty and is the
    % ingest path's job (loadImage -> cr.img.raw -> re-run pipeline), keeping
    % the schema-factory contract intact. Confirm readability either way.
    try
        px = imread(imagePath);
    catch ME
        error('NETRA:io:unreadable', ...
            'Cannot read image "%s": %s', imagePath, ME.message);
    end
    imageHash = netra.io.hashImage(px);

    eyeVal    = string(metaGet(metaStruct, 'eye', "OD"));
    phcVal    = string(metaGet(metaStruct, 'phcID', ""));
    tsVal     = datetime('now');
    % Deterministic uid when we have a PHC id; otherwise keep the Phase 0
    % timestamp+random id so mock-case paths and legacy callers still work.
    if strlength(phcVal) > 0
        seq = metaGet(metaStruct, 'seq', 0);
        uidVal = netra.io.generateUID(phcVal, tsVal, eyeVal, seq);
    else
        uidVal = localUid();
    end

    cr = struct();

    % --- meta ------------------------------------------------------------
    cr.meta = struct( ...
        'uid',        uidVal, ...
        'patientID',  metaGet(metaStruct, 'patientID', ""), ...
        'phcID',      phcVal, ...
        'age',        metaGet(metaStruct, 'age',       NaN), ...
        'dmYears',    metaGet(metaStruct, 'dmYears',   NaN), ...
        'eye',        eyeVal, ...
        'timestamp',  tsVal, ...
        'imagePath',  string(imagePath), ...
        'imageHash',  string(imageHash));

    % --- img -------------------------------------------------------------
    cr.img = struct( ...
        'raw',        zeros(0,0,3,'uint8'), ...
        'fovMask',    false(0,0), ...
        'enhanced',   zeros(0,0,3,'uint8'), ...
        'modelInput', zeros(0,0,3,'single'), ...
        'displayRGB', zeros(0,0,3,'uint8'));

    % --- quality ---------------------------------------------------------
    cr.quality = struct( ...
        'score',           NaN, ...
        'class',           "", ...
        'focus',           NaN, ...
        'illum',           NaN, ...
        'fovCompleteness', NaN, ...
        'contrast',        NaN, ...
        'quadrantMeans',   nan(1,4), ...
        'failReason',      "", ...
        'recaptureAdvice', "");

    % --- preproc ---------------------------------------------------------
    cr.preproc = struct( ...
        'appliedSteps',    strings(1,0), ...
        'claheClip',       NaN, ...
        'illumApplied',    false, ...
        'denoiseApplied',  false);

    % --- structures ------------------------------------------------------
    cr.structures = struct( ...
        'vesselMask',    false(0,0), ...
        'odCenter',      nan(1,2), ...
        'odRadius',      NaN, ...
        'foveaCenter',   nan(1,2), ...
        'maculaZone',    false(0,0), ...
        'quadrantMap',   zeros(0,0,'uint8'), ...
        'vesselDensity', NaN, ...
        'tortuosity',    NaN);

    % --- lesions ---------------------------------------------------------
    % MA = microaneurysms, HE = haemorrhages, EX = hard exudates,
    % CWS = cotton wool spots. Each is a lesion-set struct (see localLesion).
    cr.lesions = struct( ...
        'MA',  localLesion(), ...
        'HE',  localLesion(), ...
        'EX',  localLesion(), ...
        'CWS', localLesion());

    % --- grade -----------------------------------------------------------
    cr.grade = struct( ...
        'icdr',         NaN, ...
        'probs',        nan(1,5), ...
        'referableProb',NaN, ...
        'confidence',   NaN, ...
        'ruleEstimate', NaN, ...
        'disagreement', false, ...
        'label',        "");

    % --- xai -------------------------------------------------------------
    cr.xai = struct( ...
        'gradcam',         zeros(0,0,'single'), ...
        'agreementScore',  NaN, ...
        'evidenceBullets', strings(1,0), ...
        'confidenceBand',  "", ...
        'attentionSummary',"");

    % --- routing ---------------------------------------------------------
    cr.routing = struct( ...
        'decision', "", ...
        'urgency',  "", ...
        'reason',   "", ...
        'flags',    strings(1,0));

    % --- report ----------------------------------------------------------
    cr.report = struct( ...
        'pdfPath', "");

    % --- review ----------------------------------------------------------
    cr.review = struct( ...
        'action',     "", ...
        'finalGrade', NaN, ...
        'reviewerID', "", ...
        'seconds',    NaN, ...
        'note',       "", ...
        'timestamp',  NaT);

    % --- timing / provenance (one field per stage, filled by runPipeline) -
    stages = netra.util.stageNames();
    timing = struct();
    provenance = struct();
    for k = 1:numel(stages)
        timing.(stages{k})     = NaN;
        provenance.(stages{k}) = "";
    end
    timing.total = NaN;
    cr.timing     = timing;
    cr.provenance = provenance;

    % --- version ---------------------------------------------------------
    cr.version = struct( ...
        'pipelineVersion', "0.1.0-phase0", ...
        'modelHash',       "", ...
        'configHash',      "", ...
        'createdBy',       "netra.newCaseRecord");

    % --- errors (appended to by runPipeline on stage failure) ------------
    cr.errors = struct('stage', {}, 'identifier', {}, 'message', {});
end

% ------------------------------------------------------------------------
function v = metaGet(s, field, default)
%METAGET  Return s.field if present and non-empty, else the default.
    if isfield(s, field) && ~isempty(s.(field))
        v = s.(field);
    else
        v = default;
    end
end

function les = localLesion()
%LOCALLESION  Empty lesion-set struct shared by MA/HE/EX/CWS.
    les = struct( ...
        'count',       0, ...
        'totalArea',   0, ...
        'centroids',   nan(0,2), ...
        'areas',       nan(0,1), ...
        'perQuadrant', zeros(1,4), ...
        'nearMacula',  0);
end

function uid = localUid()
%LOCALUID  Deterministic-free unique id: timestamp + short random suffix.
    ts = char(datetime('now','Format','yyyyMMdd_HHmmss_SSS'));
    suffix = sprintf('%04X', randi([0, 65535]));
    uid = string(['NETRA_' ts '_' suffix]);
end
